title: MyRepo
template: Elate
readme: README.md
language: HTML
description: MY DESCRIPTION
links:
  Github: https://github.com/MyUser/MyRepo
gitauthor:
  name: 'CuboHub'
  email: 'TiagoDanin@outlook.com'
